# Generated by Django 4.2 on 2023-10-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_vendor_vid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Pid',
            new_name='pid',
        ),
    ]
