# Generated by Django 4.2 on 2023-10-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_productreview_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='qyt',
            new_name='qty',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
    ]
