# Generated by Django 4.2 on 2023-10-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ContactUs', 'verbose_name_plural': 'ContactUs'},
        ),
    ]
